# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: '2.0'

services:

  enerblock-tp:
    build: ./processor
    container_name: enerblock-python-tp
    image: enerblock-tp-image
    volumes:
      - ./processor/:/processor
    depends_on:
      - validator

  my-web-page:
    build: ./client
    image: enerblock-client
    container_name: web-client-proxy
    volumes:
      - ./client/public:/usr/local/apache2/htdocs/
    expose:
      - 80
    ports:
      - '8000:80'
    depends_on:
      - sawtooth-rest-api

  sawtooth-rest-api:
    container_name: sawtooth-rest-api
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -v
        --connect tcp://validator:4004
        --bind sawtooth-rest-api:8008

  settings-tp:
    container_name: sawtooth-settings-tp
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp -v --connect tcp://validator:4004

  validator:
    container_name: sawtooth-validator
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
    ports:
      - '4004:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen &&
        sawtooth keygen my_key &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -v \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "

  my-web-page-1:
    build: ./client1
    image: enerblock-client-1
    container_name: web-client-proxy-1
    volumes:
      - ./client1/public:/usr/local/apache2/htdocs/
    expose:
      - 80
    ports:
      - '8001:80'
    depends_on:
      - sawtooth-rest-api

  my-web-page-2:
    build: ./client2
    image: enerblock-client-2
    container_name: web-client-proxy-2
    volumes:
      - ./client2/public:/usr/local/apache2/htdocs/
    expose:
      - 80
    ports:
      - '8002:80'
    depends_on:
      - sawtooth-rest-api

  
